DROP TABLE users CASCADE;
DROP TABLE contact_details CASCADE;
DROP TABLE products CASCADE;
DROP TABLE product_images CASCADE;
DROP TABLE orders CASCADE;
DROP TABLE order_list CASCADE;
DROP TABLE carts CASCADE;
DROP TABLE cart_list CASCADE;
DROP TABLE payment_details CASCADE;
DROP TABLE session CASCADE;

DROP SEQUENCE IF EXISTS order_seq CASCADE;
DROP SEQUENCE IF EXISTS user_seq CASCADE;
DROP SEQUENCE IF EXISTS prod_seq CASCADE;