const { Client } = require('pg');
const { DB } = require('./config');

(async () => {
// -- users
    const seedUsers = `
        insert into users (is_admin, first_name, last_name, email, password, created, modified) values (false, 'Francine', 'Greave', 'fgreave0@bloglines.com', 'jaQmLEfTQ3A', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into users (is_admin, first_name, last_name, email, password, created, modified) values (false, 'Effie', 'Cozzi', 'ecozzi1@hhs.gov', 'mbXbL3ZNitv', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into users (is_admin, first_name, last_name, email, password, created, modified) values (false, 'Ajay', 'Pilley', 'apilley2@intel.com', 'q9yADkK', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into users (is_admin, first_name, last_name, email, password, created, modified) values (false, 'Jory', 'Stanworth', 'jstanworth3@bigcartel.com', 'JP5dFQCoJU', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into users (is_admin, first_name, last_name, email, password, created, modified) values (false, 'Jewelle', 'Bonar', 'jbonar4@kickstarter.com', 'vtY99P', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
    `



    // -- contact_details
    const seedContactDetails = `
        insert into contact_details (user_id, address_line1, address_line2, town_city, zip_code, country, created, modified) values ('user 1', '6 Schlimgen Park', 'Ohio', 'Columbus', '43220', 'United States', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into contact_details (user_id, address_line1, address_line2, town_city, zip_code, country, created, modified) values ('user 2', '87900 Dryden Point', 'Västerbotten', 'Umeå', '904 35', 'Sweden', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into contact_details (user_id, address_line1, address_line2, town_city, zip_code, country, created, modified) values ('user 3', '63336 Michigan Crossing', 'Nunavut', 'Kugluktuk', 'T5C', 'Canada', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
    `



    // -- products
    const seedProducts = `
        insert into products (source, product_name, type, description, price, quantity, created, modified) values ('https://www.aliexpress.com/item/1005003328710264.html', 'Winter Fur', 'Mens Top', 'Lorem ipsum dolor sit amet, duo id agam viris reformidans. No vim amet dissentiunt. Dolor temporibus nam ei, duo ea affert scribentur. Mel tale patrioque ad.\n\nIus ad placerat democritum voluptatum. Id repudiare quaerendum mei, ei mel esse harum urbanitas, ei utinam accusam detraxit usu. Duo ex elitr tritani. Cu alii ludus tempor vis, vel te elit tibique invidunt, vel id labitur facilis legendos. Sit altera mentitum phaedrum an, ei usu oblique voluptatibus. An tota rebum ornatus mel.\n\nSit tempor accumsan adipisci in, dico graece nostro ea usu. Id essent audiam voluptatum ius, cum ad sanctus perfecto, per et odio nullam appellantur. In minimum vulputate constituto has, no cum purto volumus adolescens, nec purto clita id. Ad mei omnis labore, sed cu ornatus civibus. Has feugait splendide te. Eu case facilisi pro.\n\nCu eos zril doming appareat, at vix persius pertinax moderatius, quo no modus summo praesent. Et natum oblique pro. Quod instructior per et, suas dolores petentium et has, id honestatis definitiones nec. Posse voluptua scriptorem vis ut. In deleniti perfecto vim, purto eius mel an.\n\nAnimal delenit theophrastus vel ex. Cum an labitur conclusionemque, qui natum iudico quidam an. Ceteros neglegentur te ius. Nam postea ancillae recusabo et, cu partem quaerendum duo.', 113.46, 131, TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 1', 'Fur Open Coat', 'https://ae01.alicdn.com/kf/H1431897478504b3d87aae37cffd6dc02A/New-2021-Men-s-Casual-Jacket-Fashion-Winter-Parkas-Male-Fur-Trench-Thick-Overcoat-Heated-Jackets.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 1', 'Back Fur Coat', 'https://ae01.alicdn.com/kf/H4dcc6be7ada94bf6939efed25e9d8e4ci/New-2021-Men-s-Casual-Jacket-Fashion-Winter-Parkas-Male-Fur-Trench-Thick-Overcoat-Heated-Jackets.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 1', ' Very Open Fur Coat', 'https://ae01.alicdn.com/kf/H63551a4b9b664c009238920515ffb1e64/New-2021-Men-s-Casual-Jacket-Fashion-Winter-Parkas-Male-Fur-Trench-Thick-Overcoat-Heated-Jackets.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 1', ' Detailed Fur Coat', 'https://ae01.alicdn.com/kf/Hf6f7d710504944938b22ec9699058f8bn/New-2021-Men-s-Casual-Jacket-Fashion-Winter-Parkas-Male-Fur-Trench-Thick-Overcoat-Heated-Jackets.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into products (source, product_name, type, description, price, quantity, created, modified) values ('https://www.aliexpress.com/item/1005003636300233.html', 'Winter Cotton', 'Mens Top', 'Lorem ipsum dolor sit amet, duo id agam viris reformidans. No vim amet dissentiunt. Dolor temporibus nam ei, duo ea affert scribentur. Mel tale patrioque ad.\n\nIus ad placerat democritum voluptatum. Id repudiare quaerendum mei, ei mel esse harum urbanitas, ei utinam accusam detraxit usu. Duo ex elitr tritani. Cu alii ludus tempor vis, vel te elit tibique invidunt, vel id labitur facilis legendos. Sit altera mentitum phaedrum an, ei usu oblique voluptatibus. An tota rebum ornatus mel.\n\nSit tempor accumsan adipisci in, dico graece nostro ea usu. Id essent audiam voluptatum ius, cum ad sanctus perfecto, per et odio nullam appellantur. In minimum vulputate constituto has, no cum purto volumus adolescens, nec purto clita id. Ad mei omnis labore, sed cu ornatus civibus. Has feugait splendide te. Eu case facilisi pro.\n\nCu eos zril doming appareat, at vix persius pertinax moderatius, quo no modus summo praesent. Et natum oblique pro. Quod instructior per et, suas dolores petentium et has, id honestatis definitiones nec. Posse voluptua scriptorem vis ut. In deleniti perfecto vim, purto eius mel an.\n\nAnimal delenit theophrastus vel ex. Cum an labitur conclusionemque, qui natum iudico quidam an. Ceteros neglegentur te ius. Nam postea ancillae recusabo et, cu partem quaerendum duo.', 85.26, 300, TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 2', 'Front Cotton Jacket', 'https://ae01.alicdn.com/kf/H462570adb5b546e0ac5d184a67436dffe/Men-s-Winter-Plus-Velvet-Jacket-Corduroy-Tooling-Casual-Parka-Korean-Fashion-Solid-Color-Cotton-Jacket.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 2', 'Front Open Cotton Jacket', 'https://ae01.alicdn.com/kf/He38fda4b788249ea8a7f6bc3fd68421aS/Men-s-Winter-Plus-Velvet-Jacket-Corduroy-Tooling-Casual-Parka-Korean-Fashion-Solid-Color-Cotton-Jacket.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 2', 'Back Cotton Jacket', 'https://ae01.alicdn.com/kf/H19fe91830d98489bb08d89de1a5755a55/Men-s-Winter-Plus-Velvet-Jacket-Corduroy-Tooling-Casual-Parka-Korean-Fashion-Solid-Color-Cotton-Jacket.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into products (source, product_name, type, description, price, quantity, created, modified) values ('https://www.aliexpress.com/item/1005004579158268.html', 'Camping Jacket', 'Mens Top', 'Lorem ipsum dolor sit amet, duo id agam viris reformidans. No vim amet dissentiunt. Dolor temporibus nam ei, duo ea affert scribentur. Mel tale patrioque ad.\n\nIus ad placerat democritum voluptatum. Id repudiare quaerendum mei, ei mel esse harum urbanitas, ei utinam accusam detraxit usu. Duo ex elitr tritani. Cu alii ludus tempor vis, vel te elit tibique invidunt, vel id labitur facilis legendos. Sit altera mentitum phaedrum an, ei usu oblique voluptatibus. An tota rebum ornatus mel.\n\nSit tempor accumsan adipisci in, dico graece nostro ea usu. Id essent audiam voluptatum ius, cum ad sanctus perfecto, per et odio nullam appellantur. In minimum vulputate constituto has, no cum purto volumus adolescens, nec purto clita id. Ad mei omnis labore, sed cu ornatus civibus. Has feugait splendide te. Eu case facilisi pro.\n\nCu eos zril doming appareat, at vix persius pertinax moderatius, quo no modus summo praesent. Et natum oblique pro. Quod instructior per et, suas dolores petentium et has, id honestatis definitiones nec. Posse voluptua scriptorem vis ut. In deleniti perfecto vim, purto eius mel an.\n\nAnimal delenit theophrastus vel ex. Cum an labitur conclusionemque, qui natum iudico quidam an. Ceteros neglegentur te ius. Nam postea ancillae recusabo et, cu partem quaerendum duo.', 35.64, 99, TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 3', 'White Camping Jacket', 'https://ae01.alicdn.com/kf/S551e4f959e2746208f1eaf845abb95c82/Discovery-Clothing-Outdoor-Camping-Hiking-Jacket-2022-Men-s-Breathable-Hoodie-Trench-Coat-Adventure-Jacket.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 3', 'Black Camping Jacket', 'https://ae01.alicdn.com/kf/Saccbe0ea4b034991b588efec3c0cd4af7/Discovery-Clothing-Outdoor-Camping-Hiking-Jacket-2022-Men-s-Breathable-Hoodie-Trench-Coat-Adventure-Jacket.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into products (source, product_name, type, description, price, quantity, created, modified) values ('https://www.aliexpress.com/item/1005003574138824.html', 'Leather Jacket', 'Mens Top', 'Lorem ipsum dolor sit amet, duo id agam viris reformidans. No vim amet dissentiunt. Dolor temporibus nam ei, duo ea affert scribentur. Mel tale patrioque ad.\n\nIus ad placerat democritum voluptatum. Id repudiare quaerendum mei, ei mel esse harum urbanitas, ei utinam accusam detraxit usu. Duo ex elitr tritani. Cu alii ludus tempor vis, vel te elit tibique invidunt, vel id labitur facilis legendos. Sit altera mentitum phaedrum an, ei usu oblique voluptatibus. An tota rebum ornatus mel.\n\nSit tempor accumsan adipisci in, dico graece nostro ea usu. Id essent audiam voluptatum ius, cum ad sanctus perfecto, per et odio nullam appellantur. In minimum vulputate constituto has, no cum purto volumus adolescens, nec purto clita id. Ad mei omnis labore, sed cu ornatus civibus. Has feugait splendide te. Eu case facilisi pro.\n\nCu eos zril doming appareat, at vix persius pertinax moderatius, quo no modus summo praesent. Et natum oblique pro. Quod instructior per et, suas dolores petentium et has, id honestatis definitiones nec. Posse voluptua scriptorem vis ut. In deleniti perfecto vim, purto eius mel an.\n\nAnimal delenit theophrastus vel ex. Cum an labitur conclusionemque, qui natum iudico quidam an. Ceteros neglegentur te ius. Nam postea ancillae recusabo et, cu partem quaerendum duo.', 93.45, 167, TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 4', 'Leather Banner Jacket', 'https://ae01.alicdn.com/kf/H26a06b78855e4f75b56c4848b7f7d429c/Leather-Jacket-Men-Winter-Fleece-Motorcycle-PU-Leather-Jacket-Mens-Stand-Collar-Casual-Windbreaker-Ropa-De.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 4', 'Leather Banner Jacket Zoomed In', 'https://ae01.alicdn.com/kf/Hc216e30a674d4addaeddd6988db6424eX/Leather-Jacket-Men-Winter-Fleece-Motorcycle-PU-Leather-Jacket-Mens-Stand-Collar-Casual-Windbreaker-Ropa-De.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 4', 'Leather Banner Jacket Back', 'https://ae01.alicdn.com/kf/H962b02fd420b41bd8ddbfa90268edb60X/Leather-Jacket-Men-Winter-Fleece-Motorcycle-PU-Leather-Jacket-Mens-Stand-Collar-Casual-Windbreaker-Ropa-De.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into products (source, product_name, type, description, price, quantity, created, modified) values ('https://www.aliexpress.com/item/4000120306007.html', 'Thick & Warm', 'Mens Top', 'Lorem ipsum dolor sit amet, duo id agam viris reformidans. No vim amet dissentiunt. Dolor temporibus nam ei, duo ea affert scribentur. Mel tale patrioque ad.\n\nIus ad placerat democritum voluptatum. Id repudiare quaerendum mei, ei mel esse harum urbanitas, ei utinam accusam detraxit usu. Duo ex elitr tritani. Cu alii ludus tempor vis, vel te elit tibique invidunt, vel id labitur facilis legendos. Sit altera mentitum phaedrum an, ei usu oblique voluptatibus. An tota rebum ornatus mel.\n\nSit tempor accumsan adipisci in, dico graece nostro ea usu. Id essent audiam voluptatum ius, cum ad sanctus perfecto, per et odio nullam appellantur. In minimum vulputate constituto has, no cum purto volumus adolescens, nec purto clita id. Ad mei omnis labore, sed cu ornatus civibus. Has feugait splendide te. Eu case facilisi pro.\n\nCu eos zril doming appareat, at vix persius pertinax moderatius, quo no modus summo praesent. Et natum oblique pro. Quod instructior per et, suas dolores petentium et has, id honestatis definitiones nec. Posse voluptua scriptorem vis ut. In deleniti perfecto vim, purto eius mel an.\n\nAnimal delenit theophrastus vel ex. Cum an labitur conclusionemque, qui natum iudico quidam an. Ceteros neglegentur te ius. Nam postea ancillae recusabo et, cu partem quaerendum duo.', 54.69, 281, TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 5', 'Thick Front Jacket', 'https://ae01.alicdn.com/kf/Ha6ad499296d441139ed9ceba6e108c8cG/Winter-Men-Casual-Thick-Warm-Coat-Male-Zipper-Hooded-Fleece-Long-Sleeve-Jacket-Solid-Color-Parkas.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 5', 'Thick Front And Back Jacket', 'https://ae01.alicdn.com/kf/H3ebe4ebc8a8f422d8952e912f8d31886z/Winter-Men-Casual-Thick-Warm-Coat-Male-Zipper-Hooded-Fleece-Long-Sleeve-Jacket-Solid-Color-Parkas.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into products (source, product_name, type, description, price, quantity, created, modified) values ('https://www.aliexpress.com/item/32440758658.html', 'Autumn Casual Jacket', 'Mens Top', 'Lorem ipsum dolor sit amet, duo id agam viris reformidans. No vim amet dissentiunt. Dolor temporibus nam ei, duo ea affert scribentur. Mel tale patrioque ad.\n\nIus ad placerat democritum voluptatum. Id repudiare quaerendum mei, ei mel esse harum urbanitas, ei utinam accusam detraxit usu. Duo ex elitr tritani. Cu alii ludus tempor vis, vel te elit tibique invidunt, vel id labitur facilis legendos. Sit altera mentitum phaedrum an, ei usu oblique voluptatibus. An tota rebum ornatus mel.\n\nSit tempor accumsan adipisci in, dico graece nostro ea usu. Id essent audiam voluptatum ius, cum ad sanctus perfecto, per et odio nullam appellantur. In minimum vulputate constituto has, no cum purto volumus adolescens, nec purto clita id. Ad mei omnis labore, sed cu ornatus civibus. Has feugait splendide te. Eu case facilisi pro.\n\nCu eos zril doming appareat, at vix persius pertinax moderatius, quo no modus summo praesent. Et natum oblique pro. Quod instructior per et, suas dolores petentium et has, id honestatis definitiones nec. Posse voluptua scriptorem vis ut. In deleniti perfecto vim, purto eius mel an.\n\nAnimal delenit theophrastus vel ex. Cum an labitur conclusionemque, qui natum iudico quidam an. Ceteros neglegentur te ius. Nam postea ancillae recusabo et, cu partem quaerendum duo.', 34.74, 101, TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 6', 'Blue Jacket Front', 'https://ae01.alicdn.com/kf/Hc90e4db1e8ba47af83e4d88d6e2a7db6v/2021-Spring-Autumn-Casual-Solid-Fashion-Slim-Bomber-Jacket-Men-Overcoat-New-Arrival-Baseball-Jackets-Men.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 6', 'Blue Jacket Back', 'https://ae01.alicdn.com/kf/H6f9f1ebfdd8b4172a793c975bef4ad591/2021-Spring-Autumn-Casual-Solid-Fashion-Slim-Bomber-Jacket-Men-Overcoat-New-Arrival-Baseball-Jackets-Men.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 6', 'Blue Jacket Open', 'https://ae01.alicdn.com/kf/Hcf58e38e982944b39a84289a49ec4c6eS/2021-Spring-Autumn-Casual-Solid-Fashion-Slim-Bomber-Jacket-Men-Overcoat-New-Arrival-Baseball-Jackets-Men.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into products (source, product_name, type, description, price, quantity, created, modified) values ('https://www.aliexpress.com/item/1005004665390248.html', 'Cargo Pants', 'Mens Bottom', 'Lorem ipsum dolor sit amet, duo id agam viris reformidans. No vim amet dissentiunt. Dolor temporibus nam ei, duo ea affert scribentur. Mel tale patrioque ad.\n\nIus ad placerat democritum voluptatum. Id repudiare quaerendum mei, ei mel esse harum urbanitas, ei utinam accusam detraxit usu. Duo ex elitr tritani. Cu alii ludus tempor vis, vel te elit tibique invidunt, vel id labitur facilis legendos. Sit altera mentitum phaedrum an, ei usu oblique voluptatibus. An tota rebum ornatus mel.\n\nSit tempor accumsan adipisci in, dico graece nostro ea usu. Id essent audiam voluptatum ius, cum ad sanctus perfecto, per et odio nullam appellantur. In minimum vulputate constituto has, no cum purto volumus adolescens, nec purto clita id. Ad mei omnis labore, sed cu ornatus civibus. Has feugait splendide te. Eu case facilisi pro.\n\nCu eos zril doming appareat, at vix persius pertinax moderatius, quo no modus summo praesent. Et natum oblique pro. Quod instructior per et, suas dolores petentium et has, id honestatis definitiones nec. Posse voluptua scriptorem vis ut. In deleniti perfecto vim, purto eius mel an.\n\nAnimal delenit theophrastus vel ex. Cum an labitur conclusionemque, qui natum iudico quidam an. Ceteros neglegentur te ius. Nam postea ancillae recusabo et, cu partem quaerendum duo.', 76.50, 171, TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 7', 'Cargo Pants Front', 'https://ae01.alicdn.com/kf/S4d2e003c29d644789d51ab458e87fae3K/Tactical-Cargo-Pants-Men-s-Work-Casual-Trousers-Multi-pocket-Joggers-Men-Outdoor-Wear-Resistant-Sweatpants.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 7', 'Cargo Pants Back', 'https://ae01.alicdn.com/kf/Se91c66d975fd4d708c63123756866781S/Tactical-Cargo-Pants-Men-s-Work-Casual-Trousers-Multi-pocket-Joggers-Men-Outdoor-Wear-Resistant-Sweatpants.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into products (source, product_name, type, description, price, quantity, created, modified) values ('https://www.aliexpress.com/item/1005001329995866.html', 'Work Pants', 'Mens Bottom', 'Lorem ipsum dolor sit amet, duo id agam viris reformidans. No vim amet dissentiunt. Dolor temporibus nam ei, duo ea affert scribentur. Mel tale patrioque ad.\n\nIus ad placerat democritum voluptatum. Id repudiare quaerendum mei, ei mel esse harum urbanitas, ei utinam accusam detraxit usu. Duo ex elitr tritani. Cu alii ludus tempor vis, vel te elit tibique invidunt, vel id labitur facilis legendos. Sit altera mentitum phaedrum an, ei usu oblique voluptatibus. An tota rebum ornatus mel.\n\nSit tempor accumsan adipisci in, dico graece nostro ea usu. Id essent audiam voluptatum ius, cum ad sanctus perfecto, per et odio nullam appellantur. In minimum vulputate constituto has, no cum purto volumus adolescens, nec purto clita id. Ad mei omnis labore, sed cu ornatus civibus. Has feugait splendide te. Eu case facilisi pro.\n\nCu eos zril doming appareat, at vix persius pertinax moderatius, quo no modus summo praesent. Et natum oblique pro. Quod instructior per et, suas dolores petentium et has, id honestatis definitiones nec. Posse voluptua scriptorem vis ut. In deleniti perfecto vim, purto eius mel an.\n\nAnimal delenit theophrastus vel ex. Cum an labitur conclusionemque, qui natum iudico quidam an. Ceteros neglegentur te ius. Nam postea ancillae recusabo et, cu partem quaerendum duo.', 98.61, 333, TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 8', 'Work Trousers', 'https://ae01.alicdn.com/kf/Hd9e72735ebff4ffdbec502a52a4d0b92H/2022-Cargo-Pants-Mens-Casual-Working-Pants-Fashion-Pantalon-Homme-Streetwear-Trousers-Hi-Vis-Outdoor-Electric.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 8', 'First Detail Work', 'https://ae01.alicdn.com/kf/H8958991dc1964033b013166fe78c47e7V/2022-Cargo-Pants-Mens-Casual-Working-Pants-Fashion-Pantalon-Homme-Streetwear-Trousers-Hi-Vis-Outdoor-Electric.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 8', 'Second Detail Work', 'https://ae01.alicdn.com/kf/H48d177f73f89437e98e447352b0c2e12v/2022-Cargo-Pants-Mens-Casual-Working-Pants-Fashion-Pantalon-Homme-Streetwear-Trousers-Hi-Vis-Outdoor-Electric.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 8', 'Third Detail Work', 'https://ae01.alicdn.com/kf/H54538fb4582c4d118db0f92d85d5a834M/2022-Cargo-Pants-Mens-Casual-Working-Pants-Fashion-Pantalon-Homme-Streetwear-Trousers-Hi-Vis-Outdoor-Electric.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 8', 'Fourth Detail Work', 'https://ae01.alicdn.com/kf/Ha81e8e34b87346b7b4116c92618617baP/2022-Cargo-Pants-Mens-Casual-Working-Pants-Fashion-Pantalon-Homme-Streetwear-Trousers-Hi-Vis-Outdoor-Electric.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into products (source, product_name, type, description, price, quantity, created, modified) values ('https://www.aliexpress.com/item/1005002765759012.html', 'Cargo Tech', 'Mens Bottom', 'Lorem ipsum dolor sit amet, duo id agam viris reformidans. No vim amet dissentiunt. Dolor temporibus nam ei, duo ea affert scribentur. Mel tale patrioque ad.\n\nIus ad placerat democritum voluptatum. Id repudiare quaerendum mei, ei mel esse harum urbanitas, ei utinam accusam detraxit usu. Duo ex elitr tritani. Cu alii ludus tempor vis, vel te elit tibique invidunt, vel id labitur facilis legendos. Sit altera mentitum phaedrum an, ei usu oblique voluptatibus. An tota rebum ornatus mel.\n\nSit tempor accumsan adipisci in, dico graece nostro ea usu. Id essent audiam voluptatum ius, cum ad sanctus perfecto, per et odio nullam appellantur. In minimum vulputate constituto has, no cum purto volumus adolescens, nec purto clita id. Ad mei omnis labore, sed cu ornatus civibus. Has feugait splendide te. Eu case facilisi pro.\n\nCu eos zril doming appareat, at vix persius pertinax moderatius, quo no modus summo praesent. Et natum oblique pro. Quod instructior per et, suas dolores petentium et has, id honestatis definitiones nec. Posse voluptua scriptorem vis ut. In deleniti perfecto vim, purto eius mel an.\n\nAnimal delenit theophrastus vel ex. Cum an labitur conclusionemque, qui natum iudico quidam an. Ceteros neglegentur te ius. Nam postea ancillae recusabo et, cu partem quaerendum duo.', 42.90, 230, TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 9', 'Cargo Display', 'https://ae01.alicdn.com/kf/S5f577d0bd0c24e6d8c001ab676bee0853/HOUZHOU-Black-Cargo-Pants-Men-Joggers-Hip-Hop-Techwear-Pants-Hippie-Cargo-Trousers-for-Men-Streetwear.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 9', 'Cargo Man Model One', 'https://ae01.alicdn.com/kf/S3779889909a04b26a96a7973189a991dl/HOUZHOU-Black-Cargo-Pants-Men-Joggers-Hip-Hop-Techwear-Pants-Hippie-Cargo-Trousers-for-Men-Streetwear.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 9', 'Cargo Man Model Two', 'https://ae01.alicdn.com/kf/S8527cdded30343c982d24afda7584d4ci/HOUZHOU-Black-Cargo-Pants-Men-Joggers-Hip-Hop-Techwear-Pants-Hippie-Cargo-Trousers-for-Men-Streetwear.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 9', 'Cargo Man Model Three', 'https://ae01.alicdn.com/kf/Sf9ffd67a6b984bee9a73c5f4d333b7d9f/HOUZHOU-Black-Cargo-Pants-Men-Joggers-Hip-Hop-Techwear-Pants-Hippie-Cargo-Trousers-for-Men-Streetwear.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into products (source, product_name, type, description, price, quantity, created, modified) values ('https://www.aliexpress.com/item/1005004180949612.html', 'Sweatpants', 'Wommens Bottom', 'Lorem ipsum dolor sit amet, duo id agam viris reformidans. No vim amet dissentiunt. Dolor temporibus nam ei, duo ea affert scribentur. Mel tale patrioque ad.\n\nIus ad placerat democritum voluptatum. Id repudiare quaerendum mei, ei mel esse harum urbanitas, ei utinam accusam detraxit usu. Duo ex elitr tritani. Cu alii ludus tempor vis, vel te elit tibique invidunt, vel id labitur facilis legendos. Sit altera mentitum phaedrum an, ei usu oblique voluptatibus. An tota rebum ornatus mel.\n\nSit tempor accumsan adipisci in, dico graece nostro ea usu. Id essent audiam voluptatum ius, cum ad sanctus perfecto, per et odio nullam appellantur. In minimum vulputate constituto has, no cum purto volumus adolescens, nec purto clita id. Ad mei omnis labore, sed cu ornatus civibus. Has feugait splendide te. Eu case facilisi pro.\n\nCu eos zril doming appareat, at vix persius pertinax moderatius, quo no modus summo praesent. Et natum oblique pro. Quod instructior per et, suas dolores petentium et has, id honestatis definitiones nec. Posse voluptua scriptorem vis ut. In deleniti perfecto vim, purto eius mel an.\n\nAnimal delenit theophrastus vel ex. Cum an labitur conclusionemque, qui natum iudico quidam an. Ceteros neglegentur te ius. Nam postea ancillae recusabo et, cu partem quaerendum duo.', 39.78, 200, TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 10', 'Sweaty Pants Display', 'https://ae01.alicdn.com/kf/Sc599dab545924b51bb2cf91dd3ae4cc3q.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 10', 'Sweaty Pants Button', 'https://ae01.alicdn.com/kf/Sa41354137e284a47a09a95ccf7948d31E.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 10', 'Sweaty Pants Zipper', 'https://ae01.alicdn.com/kf/Sf130a96e29d146d7ae7285a500155bb9L.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 10', 'Sweaty Pants Back', 'https://ae01.alicdn.com/kf/S10ff38c85dad4742a7d0bed224710c63f.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 10', 'Sweaty Pants Close Up', 'https://ae01.alicdn.com/kf/S98a27b9326b44e3fbfddacbedacafe6bX.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 10', 'Sweaty Pants Extreme Close Up', 'https://ae01.alicdn.com/kf/S65f11a2a8c464bc59746b225853f35ca6.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 10', 'Sweaty Pants Legs', 'https://ae01.alicdn.com/kf/Sc9edc135e3014db484c63d9166a2c267m.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 10', 'Sweaty Pants Legs Open', 'https://ae01.alicdn.com/kf/Sfa13326c737d4b1f9e52e5d9e7d00b5de.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 10', 'Sweaty Model Legs', 'https://ae01.alicdn.com/kf/Sff865ac96219450d8e945208ff66c364x/Fashion-Sweatpants-Women-Pant-Casual-Jogger-Cargo-Pants-Woman-Clothes-Trousers-Ladies-Bottom-Pantalones-Mujer-Capris.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 10', 'Sweaty Model One', 'https://ae01.alicdn.com/kf/S9138e1bb7d9747f6bf6ab8afb5c89207w/Fashion-Sweatpants-Women-Pant-Casual-Jogger-Cargo-Pants-Woman-Clothes-Trousers-Ladies-Bottom-Pantalones-Mujer-Capris.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 10', 'Sweaty Model Side Two', 'https://ae01.alicdn.com/kf/S69882ab4281b41d0a65e776e35447160n.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 10', 'Sweaty Model Stand Up Three', 'https://ae01.alicdn.com/kf/S92357795198846ff99d17764d74c4f17z.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 10', 'Sweaty Model Stand Back Four', 'https://ae01.alicdn.com/kf/Sccd053ba98b140e59d173d6ff00427fbU.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into products (source, product_name, type, description, price, quantity, created, modified) values ('https://www.aliexpress.com/item/1005003829110891.html', 'Straight Leg Cargo', 'Wommens Bottom', 'Lorem ipsum dolor sit amet, duo id agam viris reformidans. No vim amet dissentiunt. Dolor temporibus nam ei, duo ea affert scribentur. Mel tale patrioque ad.\n\nIus ad placerat democritum voluptatum. Id repudiare quaerendum mei, ei mel esse harum urbanitas, ei utinam accusam detraxit usu. Duo ex elitr tritani. Cu alii ludus tempor vis, vel te elit tibique invidunt, vel id labitur facilis legendos. Sit altera mentitum phaedrum an, ei usu oblique voluptatibus. An tota rebum ornatus mel.\n\nSit tempor accumsan adipisci in, dico graece nostro ea usu. Id essent audiam voluptatum ius, cum ad sanctus perfecto, per et odio nullam appellantur. In minimum vulputate constituto has, no cum purto volumus adolescens, nec purto clita id. Ad mei omnis labore, sed cu ornatus civibus. Has feugait splendide te. Eu case facilisi pro.\n\nCu eos zril doming appareat, at vix persius pertinax moderatius, quo no modus summo praesent. Et natum oblique pro. Quod instructior per et, suas dolores petentium et has, id honestatis definitiones nec. Posse voluptua scriptorem vis ut. In deleniti perfecto vim, purto eius mel an.\n\nAnimal delenit theophrastus vel ex. Cum an labitur conclusionemque, qui natum iudico quidam an. Ceteros neglegentur te ius. Nam postea ancillae recusabo et, cu partem quaerendum duo.', 41.34, 250, TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 11', 'Display Front And Back Straight', 'https://ae01.alicdn.com/kf/S23b14374233348888383503d24f3ccf1C.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 11', 'Straight Model One', 'https://ae01.alicdn.com/kf/Sd537df9212054c7cbaf2e976bbf81c1b1.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 11', 'Straight Model Back Two', 'https://ae01.alicdn.com/kf/S6dbb9b7f904b417eba2515bd15773c55d.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 11', 'Straight Model Back Three', 'https://ae01.alicdn.com/kf/S111a4a4fd93a4ea4a174afc61af3db46b.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into products (source, product_name, type, description, price, quantity, created, modified) values ('https://www.aliexpress.com/item/4000788883131.html', 'Red Pants', 'Wommens Bottom', 'Lorem ipsum dolor sit amet, duo id agam viris reformidans. No vim amet dissentiunt. Dolor temporibus nam ei, duo ea affert scribentur. Mel tale patrioque ad.\n\nIus ad placerat democritum voluptatum. Id repudiare quaerendum mei, ei mel esse harum urbanitas, ei utinam accusam detraxit usu. Duo ex elitr tritani. Cu alii ludus tempor vis, vel te elit tibique invidunt, vel id labitur facilis legendos. Sit altera mentitum phaedrum an, ei usu oblique voluptatibus. An tota rebum ornatus mel.\n\nSit tempor accumsan adipisci in, dico graece nostro ea usu. Id essent audiam voluptatum ius, cum ad sanctus perfecto, per et odio nullam appellantur. In minimum vulputate constituto has, no cum purto volumus adolescens, nec purto clita id. Ad mei omnis labore, sed cu ornatus civibus. Has feugait splendide te. Eu case facilisi pro.\n\nCu eos zril doming appareat, at vix persius pertinax moderatius, quo no modus summo praesent. Et natum oblique pro. Quod instructior per et, suas dolores petentium et has, id honestatis definitiones nec. Posse voluptua scriptorem vis ut. In deleniti perfecto vim, purto eius mel an.\n\nAnimal delenit theophrastus vel ex. Cum an labitur conclusionemque, qui natum iudico quidam an. Ceteros neglegentur te ius. Nam postea ancillae recusabo et, cu partem quaerendum duo.', 29.25, 350, TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 12', 'Display Red Pants', 'https://ae01.alicdn.com/kf/H47282b0085c74ecda4d5bf5aa52def18s.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 12', 'Red Pants Model', 'https://ae01.alicdn.com/kf/H71dd0067be6a4dba9e398c50d243f9c5T.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into products (source, product_name, type, description, price, quantity, created, modified) values ('https://www.aliexpress.com/item/4000790265126.html', 'Knit Tank', 'Wommens Top', 'Lorem ipsum dolor sit amet, duo id agam viris reformidans. No vim amet dissentiunt. Dolor temporibus nam ei, duo ea affert scribentur. Mel tale patrioque ad.\n\nIus ad placerat democritum voluptatum. Id repudiare quaerendum mei, ei mel esse harum urbanitas, ei utinam accusam detraxit usu. Duo ex elitr tritani. Cu alii ludus tempor vis, vel te elit tibique invidunt, vel id labitur facilis legendos. Sit altera mentitum phaedrum an, ei usu oblique voluptatibus. An tota rebum ornatus mel.\n\nSit tempor accumsan adipisci in, dico graece nostro ea usu. Id essent audiam voluptatum ius, cum ad sanctus perfecto, per et odio nullam appellantur. In minimum vulputate constituto has, no cum purto volumus adolescens, nec purto clita id. Ad mei omnis labore, sed cu ornatus civibus. Has feugait splendide te. Eu case facilisi pro.\n\nCu eos zril doming appareat, at vix persius pertinax moderatius, quo no modus summo praesent. Et natum oblique pro. Quod instructior per et, suas dolores petentium et has, id honestatis definitiones nec. Posse voluptua scriptorem vis ut. In deleniti perfecto vim, purto eius mel an.\n\nAnimal delenit theophrastus vel ex. Cum an labitur conclusionemque, qui natum iudico quidam an. Ceteros neglegentur te ius. Nam postea ancillae recusabo et, cu partem quaerendum duo.', 24.03, 300, TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 13', 'Knitty Display', 'https://ae01.alicdn.com/kf/S631a8556fdbc47ea88354a6697f28651a/korean-Bling-Lurex-diamond-Summer-knit-Tank-for-Women-Cami-Sleeveless-Knit-vest-White-Black-Women.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 13', 'Hanged Knitty', 'https://ae01.alicdn.com/kf/Sed5613d28d0b4cabaa25ae09e28e7a5ag/korean-Bling-Lurex-diamond-Summer-knit-Tank-for-Women-Cami-Sleeveless-Knit-vest-White-Black-Women.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into products (source, product_name, type, description, price, quantity, created, modified) values ('https://www.aliexpress.com/item/4000662511567.html', 'Puff Mini Dress', 'Wommens Top', 'Lorem ipsum dolor sit amet, duo id agam viris reformidans. No vim amet dissentiunt. Dolor temporibus nam ei, duo ea affert scribentur. Mel tale patrioque ad.\n\nIus ad placerat democritum voluptatum. Id repudiare quaerendum mei, ei mel esse harum urbanitas, ei utinam accusam detraxit usu. Duo ex elitr tritani. Cu alii ludus tempor vis, vel te elit tibique invidunt, vel id labitur facilis legendos. Sit altera mentitum phaedrum an, ei usu oblique voluptatibus. An tota rebum ornatus mel.\n\nSit tempor accumsan adipisci in, dico graece nostro ea usu. Id essent audiam voluptatum ius, cum ad sanctus perfecto, per et odio nullam appellantur. In minimum vulputate constituto has, no cum purto volumus adolescens, nec purto clita id. Ad mei omnis labore, sed cu ornatus civibus. Has feugait splendide te. Eu case facilisi pro.\n\nCu eos zril doming appareat, at vix persius pertinax moderatius, quo no modus summo praesent. Et natum oblique pro. Quod instructior per et, suas dolores petentium et has, id honestatis definitiones nec. Posse voluptua scriptorem vis ut. In deleniti perfecto vim, purto eius mel an.\n\nAnimal delenit theophrastus vel ex. Cum an labitur conclusionemque, qui natum iudico quidam an. Ceteros neglegentur te ius. Nam postea ancillae recusabo et, cu partem quaerendum duo.', 9.27, 100, TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 14', 'Puffy Display', 'https://ae01.alicdn.com/kf/Ha11160e611e848c1a13b2bc724e60861x.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 14', 'Puffy Mannequin Front', 'https://ae01.alicdn.com/kf/Hde55fddca3dd42f990d50c4003d74e26B/Spring-Fall-Fashion-Women-s-Solid-A-Line-Dress-Ladies-Puff-Sleeve-Button-High-Waist-Mini.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 14', 'Puffy Mannequin Back', 'https://ae01.alicdn.com/kf/Haf511f6d09d34f009c4a689b135fbeecW.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 14', 'Puffy Model Close Up', 'https://ae01.alicdn.com/kf/Hb90c6048977c4d8891f8405ea1f78cf8G.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 14', 'Puffy Model One', 'https://ae01.alicdn.com/kf/H610728450776468f87a2088f1f7200c3O.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 14', 'Puffy Model Two', 'https://ae01.alicdn.com/kf/H4992c1145758474c9cff9f85710f2f76r.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 14', 'Puffy Model Three', 'https://ae01.alicdn.com/kf/H8c6ad21bf2204584896d0dc121ccbe7bM.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 14', 'Puffy Model Combo', 'https://ae01.alicdn.com/kf/H7c236a74f5d84df7bf080175f262d6367.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into products (source, product_name, type, description, price, quantity, created, modified) values ('https://www.aliexpress.com/item/1005004139770648.html', 'V-Neck Blouse', 'Wommens Top', 'Lorem ipsum dolor sit amet, duo id agam viris reformidans. No vim amet dissentiunt. Dolor temporibus nam ei, duo ea affert scribentur. Mel tale patrioque ad.\n\nIus ad placerat democritum voluptatum. Id repudiare quaerendum mei, ei mel esse harum urbanitas, ei utinam accusam detraxit usu. Duo ex elitr tritani. Cu alii ludus tempor vis, vel te elit tibique invidunt, vel id labitur facilis legendos. Sit altera mentitum phaedrum an, ei usu oblique voluptatibus. An tota rebum ornatus mel.\n\nSit tempor accumsan adipisci in, dico graece nostro ea usu. Id essent audiam voluptatum ius, cum ad sanctus perfecto, per et odio nullam appellantur. In minimum vulputate constituto has, no cum purto volumus adolescens, nec purto clita id. Ad mei omnis labore, sed cu ornatus civibus. Has feugait splendide te. Eu case facilisi pro.\n\nCu eos zril doming appareat, at vix persius pertinax moderatius, quo no modus summo praesent. Et natum oblique pro. Quod instructior per et, suas dolores petentium et has, id honestatis definitiones nec. Posse voluptua scriptorem vis ut. In deleniti perfecto vim, purto eius mel an.\n\nAnimal delenit theophrastus vel ex. Cum an labitur conclusionemque, qui natum iudico quidam an. Ceteros neglegentur te ius. Nam postea ancillae recusabo et, cu partem quaerendum duo.', 36.30, 700, TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 15', 'V Display', 'https://ae01.alicdn.com/kf/U971817a5e37848e392b8a6575ae4229as.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 15', 'V Model One', 'https://ae01.alicdn.com/kf/U8b621a218aae4207aefde765b7f79dd74.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 15', 'V Model Two', 'https://ae01.alicdn.com/kf/U652b593c537f4fe5b18f752204949b83p.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 15', 'V Model Three', 'https://ae01.alicdn.com/kf/Uf7c25284e4974436b3999fbe5abef7d8O.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into product_images (product_id, image_name, image_data, created, modified) values ('prod 15', 'V Model Four', 'https://ae01.alicdn.com/kf/Udd3e6257d9944a07adf431eb651421a5m.jpg', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
    `




    // -- carts
    const seedCarts = `
        insert into carts (user_id, abandonded, created, modified) values ('user 1', false, TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into carts (user_id, abandonded, created, modified) values ('user 2', false, TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into carts (user_id, abandonded, created, modified) values ('user 2', true, TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into carts (user_id, abandonded, created, modified) values ('user 1', true, TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into carts (user_id, abandonded, created, modified) values ('user 3', false, TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
    `


    // -- Cart List
    const seedCartList = `
        insert into cart_list (product_id, cart_id, quantity, created, modified) values ('prod 1', 1, 3, TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into cart_list (product_id, cart_id, quantity, created, modified) values ('prod 2', 2, 5, TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into cart_list (product_id, cart_id, quantity, created, modified) values ('prod 3', 3, 6, TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into cart_list (product_id, cart_id, quantity, created, modified) values ('prod 4', 4, 1, TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into cart_list (product_id, cart_id, quantity, created, modified) values ('prod 5', 5, 3, TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into cart_list (product_id, cart_id, quantity, created, modified) values ('prod 6', 1, 4, TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into cart_list (product_id, cart_id, quantity, created, modified) values ('prod 7', 2, 1, TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into cart_list (product_id, cart_id, quantity, created, modified) values ('prod 8', 3, 3, TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into cart_list (product_id, cart_id, quantity, created, modified) values ('prod 9', 4, 3, TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into cart_list (product_id, cart_id, quantity, created, modified) values ('prod 10', 5, 6, TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
    `



    // -- Orders
    const seedOrders = `
        insert into orders (user_id, cart_id, shipping_status, final_price, total_items, tracking_id, created, modified) values ('user 1', 1, 'complete', 479.34, 7, '598815437-9', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into orders (user_id, cart_id, shipping_status, final_price, total_items, tracking_id, created, modified) values ('user 2', 2, 'complete', 502.80, 6, '755306191-3', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into orders (user_id, cart_id, shipping_status, final_price, total_items, tracking_id, created, modified) values ('user 3', 5, 'pending', 402.75, 9, 'not available', TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
    `



    // -- Order List
    const seedOrderList = `
        insert into order_list (product_id, order_id, quantity, price, created, modified) values ('prod 1', 'order 1', 3, 340.38, TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into order_list (product_id, order_id, quantity, price, created, modified) values ('prod 6', 'order 1', 4, 138.96, TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into order_list (product_id, order_id, quantity, price, created, modified) values ('prod 7', 'order 2', 1, 76.50, TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into order_list (product_id, order_id, quantity, price, created, modified) values ('prod 2', 'order 2', 5, 426.30, TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into order_list (product_id, order_id, quantity, price, created, modified) values ('prod 5', 'order 3', 3, 164.07, TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into order_list (product_id, order_id, quantity, price, created, modified) values ('prod 10', 'order 3', 6, 238.68, TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
    `




    // -- Payment details
    const seedPaymentDetails = `
        insert into payment_details (user_id, card_type, card_number, expiry_date, name_on_card, cvv, created, modified) values ('user 1', 'solo', '6334898910023035670', '2024-07', 'Carlin Amner', 765, TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into payment_details (user_id, card_type, card_number, expiry_date, name_on_card, cvv, created, modified) values ('user 2', 'visa-electron', '4844119113936041', '2025-06', 'Octavia Keightley', 920, TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
        insert into payment_details (user_id, card_type, card_number, expiry_date, name_on_card, cvv, created, modified) values ('user 3', 'jcb', '3580755232310681', '2023-01', 'Evin Burghill', 593, TO_DATE('17/12/2021', 'DD/MM/YYYY'), TO_DATE('29/04/2022', 'DD/MM/YYYY'));
    `


    try {
        const db = new Client({
            host: DB.PGHOST,
            user: DB.PGUSER,
            database: DB.PGDATABASE,
            password: DB.PGPASSWORD,
            port: DB.PGPORT
        });
        
        // Opening connection
        await db.connect();

        // Seeding all to their tables
        await db.query(seedUsers);
        await db.query(seedContactDetails);
        await db.query(seedProducts);
        await db.query(seedCarts);
        await db.query(seedCartList);
        await db.query(seedOrders);
        await db.query(seedOrderList);
        await db.query(seedPaymentDetails);

        // Closing Connection
        await db.end();

    } catch (err) {
        console.log("ERROR SEEDING FOR ONE OR MORE TABLES: ", err)
    }

})();